version: "3.9"

services:
  db:
    image: postgres
    container_name: test_task_postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - postgres.env
    ports:
      - "15432:5432"

  web:
    build: .
    container_name: test_task_django
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - postgres.env
      - platform.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
